### ISSUE TITLE
train with customize dataset:I have changed the classes and num_classes, but got this mistake

### ISSUE THREAD

**Issue by zhp12343** [Sense-X/Co-DETR#10]
AssertionError: The `num_classes` (10) in CoDeformDETRHead of MMDistributedDataParallel does not matches the length of `CLASSES` 1) in CocoDataset

**Comment by TempleX98** [comment]
You need to modify the classes of CocoDataset following [official instructions](https://github.com/open-mmlab/mmdetection/blob/f78af7785ada87f1ced75a2313746e4ba3149760/docs/en/advanced_guides/customize_dataset.md)

**Comment by zhp12343** [comment]
> 
It is not the reason of cocodataset.
I remove ''custom_hooks = [dict(type='NumClassCheckHook')]'' in configs/_base_/default_runtime.py.
Then I solves this problem.
