### ISSUE TITLE
How much GPU memory is needed?

### ISSUE THREAD

**Issue by dedoogong** [Sense-X/Co-DETR#103]
Hello ! thanks for your great work!
I'm trying to train ViT Co DETR using 4 V100 with LVIS v1 dataset but I met OOM. 
How much GPU memory do I need? or What GPU did you use for  training ViT CoDETR?

Thank you!

**Comment by TempleX98** [comment]
We use A100 80G GPUs for the ViT model training (LVIS). Some techniques, such as FSDP, can help you reduce training memory consumption. Please refer to the [latest mmdetection v3](https://github.com/open-mmlab/mmdetection/tree/v3.2.0/projects/example_largemodel) for more details.

**Comment by dedoogong** [comment]
Thank you very very much for your kind reply!
