### ISSUE TITLE
 freeze most of the layers and train head

### ISSUE THREAD

**Issue by Qia98** [Sense-X/Co-DETR#109]
I would like to train on a custom dataset, but I want to freeze most of the layers and only train the last few layers (like head or decoder). I hope that the mAP or AP metric can reach the results of training the YOLO model on the same dataset. Is this feasible?

**Comment by TempleX98** [comment]
I have yet to explore this configuration. Perhaps you can perform this experiment using your custom dataset to benchmark this setting.
