### ISSUE TITLE
object detection on small object

### ISSUE THREAD

**Issue by zhp12343** [Sense-X/Co-DETR#11]
I want to know the performance between co_deformable_detr_swin_large_1x_coco and co_deformable_detr_swin_base_3x_coco, which is better on small object?
Thanks!

**Comment by TempleX98** [comment]
swin base 3x: bbox_mAP_s 41.3
swin large 1x: bbox_mAP_s 40.1

**Comment by zhp12343** [comment]
> swin base 3x: bbox_mAP_s 41.3 swin large 1x: bbox_mAP_s 40.1

Thanks!
