### ISSUE TITLE
Training memory requirement

### ISSUE THREAD

**Issue by SamedYalcin** [Sense-X/Co-DETR#121]
Hi,

I'm trying to train your model on Kaggle with P100 w\16GB VRAM however I'm running out of memory. Can you share the memory requirements and if possible tips to reduce memory required? 

Attached below is the model I'm trying to train. Instead of `train.sh`, I'm using `train.py.`

![image](https://github.com/Sense-X/Co-DETR/assets/55953505/bcc002d2-4131-4f92-8cfd-0bae7cb081d2)

**Comment by TempleX98** [comment]
We use A100 80G GPUs to train Swin-L and ViT-L models. You can reduce the image size to 1333x800 or freeze the backbone during training. Besides, some techniques such as FSDP and FP16, can help you reduce training memory consumption. Please refer to the [latest mmdetection v3](https://github.com/open-mmlab/mmdetection/tree/v3.2.0/projects/example_largemodel) for more details.

**Comment by SamedYalcin** [comment]
Reducing image size helps for a few batches but after a while it fails again. I will try freezing the backbone. For your last suggestion, does this repo work on MMDetectionV3?

**Comment by TempleX98** [comment]
Sure, please refer to https://github.com/open-mmlab/mmdetection/tree/main/projects/CO-DETR

**Comment by SamedYalcin** [comment]
I wasn't able to find it under Model Zoo. Thanks for pointing out and thanks for the help. 

![image](https://github.com/Sense-X/Co-DETR/assets/55953505/b9488b1c-bed0-4ed4-839e-4dabedb3d43e)
MMDetection repo seems to use `co_dino_5scale_swin_large_16e_o365tococo.pth` instead of `co_dino_5scale_swin_large_22e_o365.pth`. Is this a mistake? `co_dino_5scale_swin_large_16e_o365tococo.pth` seems to use Object365 labels where as `co_dino_5scale_swin_large_22e_o365.pth` uses COCO labels. The config is for COCO.

**Comment by SamedYalcin** [comment]
Edited the comment.

**Comment by TempleX98** [comment]
This config is used to finetune the Objects365 pretrained Swin-L on the COCO dataset.
If you want to train this model on your custom dataset, I recommend using `co_dino_5scale_swin_large_16e_o365tococo.pth` for better performance.

**Comment by SamedYalcin** [comment]
For new comers:

- Gradient checkpointing or reducing image size alone is not enough to train with 16GB of VRAM. I had to freeze the backbone completely, enable checkpointing and reduce the image size to 1333x800. Memory usage peaked around ~15GB.
- Automatic Mixed Precision traning throws a runtime error. Maybe it's not supported?
- I cannot comment of FSDP as I train on a single GPU and from my understading I need to use distributed training to enable FSDP.

Thanks for the help @TempleX98. Feel free to close the issue at your convenience.

**Comment by daniel-bogdoll** [comment]
Hey @SamedYalcin (or maybe @TempleX98), would it be possible to share a config file for training with ```co_dino_5scale_vit_large_coco.py``` with the changes you mentioned?
