### ISSUE TITLE
Which one in config is co-detr?

### ISSUE THREAD

**Issue by Code-of-Liujie** [Sense-X/Co-DETR#122]
Which one in config is co-detr?

**Comment by TempleX98** [comment]
ResNet-50 + 1x schedule: projects/configs/co_dino/co_dino_5scale_r50_1x_coco.py
Swin-L + 1x schedule: projects/configs/co_dino/co_dino_5scale_swin_large_1x_coco.py
Swin-L + 3x schedule: projects/configs/co_dino/co_dino_5scale_swin_large_3x_coco.py
