### ISSUE TITLE
Collaborative Hybrid Assignments Training 问题

### ISSUE THREAD

**Issue by Morizhaoyang** [Sense-X/Co-DETR#124]
想问下，Collaborative Hybrid Assignments Training章节中，
1. 这里的预测头只是针对辅助分支的吗？如果是的话，为什么不是所有都是用
2. 这个辅助头是encoder后面接的？用encoder的结果得到分类和框的结果，然后进行样本筛选？
3. Lenc loss的含义是什么?

**Comment by TempleX98** [comment]
1. 如果所有都用，首先会增加比较多的训练时间。其次，不同预测头的标签分配策略不同，所有都用会导致优化冲突加剧从而降低性能
2. 辅助头的输入是encoder输出的feature，输出得到分类回归结果之后进行标签分配然后计算loss
3. 辅助分支总的loss
