### ISSUE TITLE
Why doesn't best.pth File Automatically Generate?

### ISSUE THREAD

**Issue by jeonga0303** [Sense-X/Co-DETR#125]
I'm encountering an issue where the best.pth file does not automatically generate as expected in my project. 
Despite following the usual procedures and ensuring my configurations are correctly set, this file, which should represent the best model state based on validation performance, is not being created. 
Could there be a specific reason for this, or is there a step I might be missing? 
Any insights or suggestions on how to troubleshoot this problem would be greatly appreciated.

<img width="230" alt="image" src="https://github.com/Sense-X/Co-DETR/assets/52391624/1c3e2927-85d9-447c-b4e7-56896a7eb085">

Additionally, I've noticed that my logs do not display class-wise accuracy, which is crucial for a detailed analysis of my model's performance across different categories. 
I am unsure if this feature requires additional configuration or if it's a limitation of the tools I'm using. 
Could someone advise on how to enable or set up logging to include class-wise accuracy? 
Detailed steps or references to documentation would be extremely helpful.

**Comment by TempleX98** [comment]
The [CheckpointHook](https://github.com/open-mmlab/mmcv/blob/9ecd6b0d5ff9d2172c49a182eaa669e9f27bb8e7/mmcv/runner/hooks/checkpoint.py#L9) of [MMDetection V2.25.3](https://github.com/open-mmlab/mmdetection/releases/tag/v2.25.3) can not save the best checkpoint by default. I recommend you use the Co-DETR implemented by MMDetection V3, which supports such checkpoint saving features.

**Comment by jeonga0303** [comment]
Okay, Thanks.

<img width="170" alt="image" src="https://github.com/Sense-X/Co-DETR/assets/52391624/d9d1c347-1cdf-4ed7-8b9c-3d1be34c80e6">

**Comment by jeonga0303** [comment]
> The [CheckpointHook](https://github.com/open-mmlab/mmcv/blob/9ecd6b0d5ff9d2172c49a182eaa669e9f27bb8e7/mmcv/runner/hooks/checkpoint.py#L9) of [MMDetection V2.25.3](https://github.com/open-mmlab/mmdetection/releases/tag/v2.25.3) can not save the best checkpoint by default. I recommend you use the Co-DETR implemented by MMDetection V3, which supports such checkpoint saving features.

my mmdet was an older version. 
Thanks for letting me know.

<img width="170" alt="image" src="https://github.com/Sense-X/Co-DETR/assets/52391624/9eadf881-9601-4d92-ab7a-d5ca28dd66bf">

**Comment by jeonga0303** [comment]
@TempleX98 

Are you saying that the 'best.pth' file is generated starting from mmdetection version 3.x.x?  I think that's incorrect. 
I added the checkpoint_config option to config file to automatically generate the 'best.pth' file, and it was automatically created. 

`checkpoint_config = dict(
    interval=1,
    max_keep_ckpts=3,
    save_last=True,
)`
