### ISSUE TITLE
frozen ViT-L backbone

### ISSUE THREAD

**Issue by hubhub086** [Sense-X/Co-DETR#126]
hello! I want to freeze the backbone of Co-DETR-ViT-L，so how can I do it? Is there any method like the `frozen_stages` in Resnet backbone?

**Comment by hubhub086** [comment]
can I simply add this code?
![Snipaste_2024-03-27_13-40-01](https://github.com/Sense-X/Co-DETR/assets/81469832/0c00dd7d-3e2b-4ffa-aebc-1f915514e091)

**Comment by TempleX98** [comment]
Freezing the backbone has been implemented in `_freeze_stages` of `mmdet/models/backbones/swin.py`.

**Comment by hubhub086** [comment]
Thanks!
