### ISSUE TITLE
KeyError: 'MotionDiffusion is not in the models registry'

### ISSUE THREAD

**Issue by jiahui010406** [Sense-X/Co-DETR#127]
<img width="732" alt="Screenshot 2024-03-29 at 2 34 16 AM" src="https://github.com/Sense-X/Co-DETR/assets/78160829/896f744f-f075-4e18-a491-931d67df1473">
I am facing this issue when running visualisation of ReMoDiffuse.
I have tried for many ways but still cannot solve it.
__init__.py is checked and @ARCHITECTURES.register_module() written.

**Comment by TempleX98** [comment]
I am not familiar with the RemoDiffuse codebase. You can create a new issue in the repo of RemoDiffuse for help.
