### ISSUE TITLE
AssertionError: scope builder exists in model registry

### ISSUE THREAD

**Issue by jiahui010406** [Sense-X/Co-DETR#128]
<img width="732" alt="Screenshot 2024-03-29 at 3 41 42 AM" src="https://github.com/Sense-X/Co-DETR/assets/78160829/26a22a5c-a207-4e00-a340-a5cddcf6d257">
Issue appeared when running train.py of RemoDiffuse
Any hints why is it coming?

**Comment by TempleX98** [comment]
I am not familiar with the RemoDiffuse codebase. You can create a new issue in the repo of RemoDiffuse for help.
