### ISSUE TITLE
OpenAI api.Connection Error 国内无法连接

### ISSUE THREAD

**Issue by jiahui010406** [Sense-X/Co-DETR#129]
<img width="723" alt="Screenshot 2024-04-01 at 4 51 36 PM" src="https://github.com/Sense-X/Co-DETR/assets/78160829/75bc482d-6192-46d4-9aed-4d8765df97a8">
proxy mentioned，proxies已经在代码特别注明了
<img width="723" alt="Screenshot 2024-04-01 at 4 52 07 PM" src="https://github.com/Sense-X/Co-DETR/assets/78160829/df48e83d-1404-413e-886a-0b45c1c6c74c">
rules written，规则我也写了，
I think vpn is not the problem, I can connect every url using curl, even connecting api.openai.com. But connection error still appears when async api.
在curl连接和各种vpn检查都做了，vpn是没问题的，但只要一调用api，就会出现connection error，还有什么办法吗？

**Comment by TempleX98** [comment]
你好，你的这几个issue是不是发错位置了，我看都是和RemoDiffuse相关的。

**Comment by jiahui010406** [comment]
奥奥 不好意思
