### ISSUE TITLE
Inference code demo

### ISSUE THREAD

**Issue by zhaochunhai** [Sense-X/Co-DETR#13]
Could you please post the code for inference on images and videos?

**Comment by TempleX98** [comment]
You can use the mmdetection official inference demo: demo/image_demo.py and demo/video_demo.py

**Comment by zhaochunhai** [comment]
> You can use the mmdetection official inference demo: demo/image_demo.py and demo/video_demo.py

'CoDETR is not in the models registry'，

Thank you, but how to solve this error.

**Comment by TempleX98** [comment]
fix it

**Comment by abdulbasit0369** [comment]
Facing similar problem. Can you tell me how to fix this? @zhaochunhai

**Comment by zhaochunhai** [comment]
> Facing similar problem. Can you tell me how to fix this? @zhaochunhai

from projects import *

Add the line under File  ./Co-DETR/mmdet/apis/inference.py
