### ISSUE TITLE
Running on CPU

### ISSUE THREAD

**Issue by bibekyess** [Sense-X/Co-DETR#130]
Hello! 

Thanks for your awesome work. I am using this for my custom use and accuracy wise, it is very satisfactory. But, in terms of speed, it is very slow.
In CPU, Co-Dino with SwinL backbone takes around 2s. Using `mmdet` package, I can convert it to onnx and tensorrt. But onnx model also didn't result in speed improvement.
So, I want to ask for the author's recommended approach for running Co-Detr faster on CPUs?
Is it possible to export it to openvino? Current `mmdet` version doesn't support export to openvino. If there are any suggestions, I would highly appreciate it.

 Thank you!

**Comment by TempleX98** [comment]
Sorry for the late reply. I have never run a detector on the CPU. I think a possible solution is to convert the Co-DINO weights to the DINO format and export this DINO model to openvino via [mmdeploy](https://github.com/open-mmlab/mmdeploy/blob/main/docs/en/04-supported-codebases/mmdet.md).

**Comment by bibekyess** [comment]
Ok, sounds like a good direction to try. Thank you for your response!
