### ISSUE TITLE
Flops计算

### ISSUE THREAD

**Issue by Idcogroup** [Sense-X/Co-DETR#131]
请问CO-DINO-R50的FLOPS是多少，测试了很多遍都是报错或者0FLops。

**Comment by TempleX98** [comment]
目前mmdet里对于某些算子的flops计算有问题，比如deformable attention，co-dino的flops可以参考dino的flops，因为co-detr在infer的时候不引入额外计算

**Comment by Idcogroup** [comment]
好的，谢谢！！
