### ISSUE TITLE
encoder co deformable detr

### ISSUE THREAD

**Issue by prsbsvrn** [Sense-X/Co-DETR#138]
Hello,

I am interested in customizing the encoder used in your project. Specifically, I would like to know if it's possible to replace or modify the existing encoder implementation, which relies on mmcv, with my own custom implementation. Could you please confirm if such a modification is feasible and, if so, provide any guidance or considerations I should be aware of?

Thank you!

**Comment by TempleX98** [comment]
Sure, you can replace the deformable encoder with your custom implementation. Please make sure you understand the effect of each input and output variable of the [deformable encoder](https://github.com/Sense-X/Co-DETR/blob/d01ef8b657cc3711c59759cf863fe5ab9aa50e76/projects/models/transformer.py#L284) when you modify its architecture.
