### ISSUE TITLE
About the part of instance segmentaion

### ISSUE THREAD

**Issue by GisRookie** [Sense-X/Co-DETR#15]
Firstly, thanks for you great work, and i want to know about when the code of instance segmentation will release？

**Comment by GisRookie** [comment]
Firstly, thanks for your great work, and i want to konw when the code of instance segmentation will  release？

**Comment by TempleX98** [comment]
We provide the config for Co-DETR with auxiliary mask branch: projects/configs/co_deformable_detr/co_deformable_detr_mask_r50_1x_coco.py. You can evaluate the roi_head after training.

**Comment by GisRookie** [comment]
Thank you very much!

**Comment by GisRookie** [comment]
How can i evaluate the roi head?
when i run ./tools/dist_test.sh work_dir/co_deformable_detr_mask_r50_1x_coco.py work_dir/epoch_1.pth 3 --eval bbox segm
error:
in evaluate_det_segm
    raise KeyError(f'{metric} is not in results')
KeyError: 'segm is not in results'

and i print the result_file:
{'bbox': '/tmp/tmp75forie2/results.bbox.json', 'proposal': '/tmp/tmp75forie2/results.bbox.json'}

**Comment by TempleX98** [comment]
You can set `eval_module="two-stage"` following this [code](https://github.com/Sense-X/Co-DETR/blob/3b3c47e64b3d34d2c6f7c27067b6f03d5d3e5811/projects/models/co_detr.py#L30)

**Comment by GisRookie** [comment]
it works, thank you very much.
