### ISSUE TITLE
how to use DETR aug with vit pretrain?

### ISSUE THREAD

**Issue by egbertYeah** [Sense-X/Co-DETR#150]
作者你好，vit提供的config支持的LSJ数据增强，但是我的目标检测数据集没有mask，想问一下怎么关闭分割，或者如何使用DETR增强？谢谢

**Comment by TempleX98** [comment]
请参考这个config的注释部分：https://github.com/Sense-X/Co-DETR/blob/d01ef8b657cc3711c59759cf863fe5ab9aa50e76/projects/configs/co_dino/co_dino_5scale_lsj_r50_1x_coco.py#L68

**Comment by egbertYeah** [comment]
> 请参考这个config的注释部分：
> 
> https://github.com/Sense-X/Co-DETR/blob/d01ef8b657cc3711c59759cf863fe5ab9aa50e76/projects/configs/co_dino/co_dino_5scale_lsj_r50_1x_coco.py#L68
好的，非常感谢
