### ISSUE TITLE
"Update hf models" commit introduced a bug

### ISSUE THREAD

**Issue by Asha-Gutlapalli** [Sense-X/Co-DETR#151]
I believe this recent [commit - Update hf models](https://github.com/Sense-X/Co-DETR/commit/53d6e90871a933b15d360398058a97370a24e3a5) may have introduced a bug in [`projects/models/co_detr.py`](https://github.com/Sense-X/Co-DETR/blob/main/projects/models/co_detr.py#L254). 

While training the Co-Deformable-DETR model with Swin-T backbone, the script throws an error at this line. 
```
bbox_losses, x, results_list = self.query_head.forward_train(x, img_metas, gt_bboxes, gt_labels, gt_bboxes_ignore)

ValueError: not enough values to unpack (expected 3, got 2)
```

**Comment by TempleX98** [comment]
Thank you for raising the issue. I have fixed this bug.
