### ISSUE TITLE
预训练权重无法加载到

### ISSUE THREAD

**Issue by Whitefish-by** [Sense-X/Co-DETR#153]
我刚开始使用co-deformable-swin-large-1x训练了12个epoch，得到epoch12.pth（结束时候loss为41左右），之后我将前面得到的模型作为预训练模型，继续使用相同的数据集训练12epoch，这时候开始训练的loss竟然达到了148，也就是完全从0开始训练时候的Loss，最终结果观察到也是仍然和第一次的epoch12.pth一模一样。
请问这个什么原因导致的？
与此同时，训练开始的时候的第一个epoch不论什么模型都是mAP全部是0.0000，我怀疑模型并没有加载预训练权重或者checkpoint。
请您帮我看看这是什么问题导致的。万分感谢您！

**Comment by TempleX98** [comment]
你在config里面有通过load_from参数指明预训练模型吗

**Comment by Whitefish-by** [comment]
我看默认的配置文件里没有load_from，我设置了pretrained="xxxx"参数和use_checkpoint=True，原来需要设置load_from参数，非常感谢您的指导！

**Comment by lancer121387** [comment]
训练时，在哪个配置文件里加载了Load_from所指明的预训练模型呢

**Comment by TempleX98** [comment]
需要在你训练的config里通过添加`load_from=/path/checkpoint`，来指明预训练模型，model zoo里提供了对应的coco预训练模型
