### ISSUE TITLE
Instance Segmentation Results

### ISSUE THREAD

**Issue by Madave94** [Sense-X/Co-DETR#163]
I was trying to run the instance segmentation Co-DETR model pre-trained on Objects365 for LVIS. For this I used this config _projects/configs/co_dino_vit/co_dino_5scale_lsj_vit_large_lvis_instance.py_ and this weights https://huggingface.co/zongzhuofan/co-detr-vit-large-lvis-instance .

I ran the following command `bash tools/dist_test.sh projects/configs/co_dino_vit/co_dino_5scale_lsj_vit_large_lvis_instance.py weights/co-detr-vit-large-coco-instance.pth 2 --eval segm`

Somehow, I got results at 41.1 instead of 60.7 on the instance segmentation results. Any idea what could be wrong? I have attached the logging I received from the standard output.

[log_co_detr_lsj_vit_large_lvis_instance.txt](https://github.com/user-attachments/files/16881113/log_co_detr_lsj_vit_large_lvis_instance.txt)

**Comment by TempleX98** [comment]
I can get correct results using my local codebase. I think there is a bug in this repo and I will check it ASAP.

**Comment by Madave94** [comment]
Thanks for the quick reply. I also re-checked my installed libraries. My mmcv-full, mmdet, pytorch and python version align exactly with the `README.md` specification. Only my cuda version is newer at 12.4, however, as far as I know they are backward compatible, so this should not cause issues.

**Comment by TempleX98** [comment]
@Madave94 Hi, I have fixed this bug. Please update the codes and try again.

**Comment by Madave94** [comment]
Thanks, with the bug fix I was able to reproduce the results.

**Comment by Lizhinwafu** [comment]
Our server's CUDA only provides versions greater than 12. How should we configure the environment?
