### ISSUE TITLE
Performance of Swin-L

### ISSUE THREAD

**Issue by dawn-ech** [Sense-X/Co-DETR#17]
Hi @TempleX98, thanks for your awesome work. 
Co-DINO with ViT-L achieves 66.0%AP.  I would like to know the performance of Co-DINO with Swin-L. Thank you.

**Comment by TempleX98** [comment]
We don't have the result of O365 pretrianed Co-DETR+Swin-L

**Comment by HITerStudy** [comment]
> We don't have the result of O365 pretrained Co-DETR+Swin-L

The training pipeline for the 66.0% AP of Co-Dino(ViT-L) is same as that in this respository? such as image resolution and multi-scale range in data augmentation? Please offer some details, thanks!

**Comment by TempleX98** [comment]
> > We don't have the result of O365 pretrained Co-DETR+Swin-L
> 
> The training pipeline for the 66.0% AP of Co-Dino(ViT-L) is same as that in this respository? such as image resolution and multi-scale range in data augmentation? Please offer some details, thanks!

It's the same model as the released part. The image resolution for pretraining is [480, 1024]x1280. We will update the results and model details in the arxiv version soon.

**Comment by HITerStudy** [comment]
> > > We don't have the result of O365 pretrained Co-DETR+Swin-L
> > 
> > 
> > The training pipeline for the 66.0% AP of Co-Dino(ViT-L) is same as that in this respository? such as image resolution and multi-scale range in data augmentation? Please offer some details, thanks!
> 
> It's the same model as the released part. The image resolution for pretraining is [480, 1024]x1280. We will update the results and model details in the arxiv version soon.

the pretraining dataset is obj365, it is the v1 version or obj365v2?

**Comment by TempleX98** [comment]
> > > > We don't have the result of O365 pretrained Co-DETR+Swin-L
> > > 
> > > 
> > > The training pipeline for the 66.0% AP of Co-Dino(ViT-L) is same as that in this respository? such as image resolution and multi-scale range in data augmentation? Please offer some details, thanks!
> > 
> > 
> > It's the same model as the released part. The image resolution for pretraining is [480, 1024]x1280. We will update the results and model details in the arxiv version soon.
> 
> the pretraining dataset is obj365, it is the v1 version or obj365v2?

v2

**Comment by songyuc** [comment]
Hi, @TempleX98, have the model config and weight of 66.0 boxAP been released?

**Comment by TempleX98** [comment]
@songyuc Sorry, we have no plan to release the ViT-L model now. But we may release another O365 pretrained model in a few weeks.

**Comment by songyuc** [comment]
Thanks sincerely.

**Comment by TempleX98** [comment]
@dawn-ech @songyuc We have provided the O365 pre-trained Swin-L model

**Comment by ganliqiang** [comment]
hi ,i cannot find the pretrain model swin_large_patch4_window12_384_22k.pth so,the leatest model swin_large_patch4_window12_384_22k.pth is same as the pretrained model in the config file.how i download the swin_large_patch4_window12_384_22k.pth.thanks a lot in advanced.

**Comment by TempleX98** [comment]
@ganliqiang  https://github.com/SwinTransformer/storage/releases/download/v1.0.0/swin_large_patch4_window12_384_22k.pth
