### ISSUE TITLE
When the training config for instance segmentation will be released?

### ISSUE THREAD

**Issue by shallweiwei** [Sense-X/Co-DETR#172]
I noticed that the instance segmentation metric is very high, and I also want to try training, but it seems that the annotation below says "(test)", which means it can only be used for inference, right?

**Comment by TempleX98** [comment]
This config is labeled as "test" since some techniques used for long-tail dataset training are not included. It can be used for training on your custom dataset.

**Comment by shallweiwei** [comment]
Thank you for your answer. I'll try to use it.
