### ISSUE TITLE
Did you use Faster-rcnn head as aux head in this repo?

### ISSUE THREAD

**Issue by Artificial-Inability** [Sense-X/Co-DETR#18]
The best aux head setting is ATSS+Faster-rcnn in the paper, in which co-deformable-detr could achieve 49.5 in coco 1x. It seems that the config in this repo only contains ATSS head and still achieves 49.5 (in the paper only ATSS head setting has 48.7AP). Which setting did you use as a final version (i.e. the setting you used to train co-dino to 66.0AP)?

**Comment by TempleX98** [comment]
`CoStandardRoIHead` is the Faster-RCNN head. 
The final setting is `projects/configs/co_dino/co_dino_5scale_swin_large_3x_coco.py`.
