### ISSUE TITLE
AttributeError: 'ConfigDict' object has no attribute 'optimizer_config'

### ISSUE THREAD

**Issue by jih0-kim** [Sense-X/Co-DETR#181]
Hi, thank you for your amazing work on this project!

I’m currently training Co-DETR with my own dataset. Initially, I trained it using the `projects/configs/co_deformable_detr/co_deformable_detr_r50_1x_coco.py` config file, and it ended well, fortunately. Now, I'm attempting to train with `projects/configs/co_dino_vit/co_dino_5scale_vit_large_coco.py`, but I encountered an error as shown below.

```
Traceback (most recent call last):
  File "tools/train.py", line 245, in <module>
    main()
  File "tools/train.py", line 234, in main
    train_detector(
  File "/ws/mmdet/apis/train.py", line 187, in train_detector
    elif distributed and 'type' not in cfg.optimizer_config:
  File "/opt/conda/lib/python3.8/site-packages/mmcv/utils/config.py", line 513, in __getattr__
    return getattr(self._cfg_dict, name)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/utils/config.py", line 49, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'optimizer_config'
```

To resolve this, would simply adding `optimizer_config = dict(grad_clip=dict(max_norm=0.1, norm_type=2))` to the config file be sufficient, or would additional changes be necessary?

**Comment by TempleX98** [comment]
I have updated the `optimizer_config` in the latest commit, please have a try

**Comment by jih0-kim** [comment]
Thanks for the quick update. It works for me now.
