### ISSUE TITLE
Training Co-DINO, The classification weight for loss and matcher should beexactly the same

### ISSUE THREAD

**Issue by bluceliuljx** [Sense-X/Co-DETR#19]
![image](https://github.com/Sense-X/Co-DETR/assets/40584477/aeb45843-8a13-4c08-ba75-37bd1e07cd6d)
AssertionError: The classification weight for loss and matcher should beexactly the same.

AssertionError: CoDINOHead: The classification weight for loss and matcher should beexactly the same.

AssertionError: CoDETR: CoDINOHead: The classification weight for loss and matcher should beexactly the same.

**Comment by TempleX98** [comment]
You should delete these assertions in `detr.py`

**Comment by bluceliuljx** [comment]
![image](https://github.com/Sense-X/Co-DETR/assets/40584477/018cca7a-02d3-4ea2-a2e2-0fc72b8b49c5)
yeah！
loss_cls['loss_weight'] == assigner['cls_cost']['weight']
