### ISSUE TITLE
Can find Co-DINO Swin-L LVIS config~~~ 

### ISSUE THREAD

**Issue by aixiaodewugege** [Sense-X/Co-DETR#21]
Hi, I noticed that you shared the following model,

Co-DINO	Swin-L	36	LSJ	LVIS	56.9	config

But I want to use this model to detect classes in LVIS, is there any way that I could use it?

Thanks~~

**Comment by TempleX98** [comment]
You can use [co_dino_5scale_lsj_swin_large_3x_coco.py](https://github.com/Sense-X/Co-DETR/blob/main/projects/configs/co_dino/co_dino_5scale_lsj_swin_large_3x_coco.py) and modify the `num_classes` ('num_classes=1203')

**Comment by aixiaodewugege** [comment]
Thanks for your reply

I mean the config here, I don't want to train the model, I just want to use it for inference~~
![image](https://github.com/Sense-X/Co-DETR/assets/47085237/287a68a0-6861-4070-819c-e4f6b3719a7f)

**Comment by TempleX98** [comment]
> Thanks for your reply
> 
> I mean the config here, I don't want to train the model, I just want to use it for inference~~ ![image](https://user-images.githubusercontent.com/47085237/256438240-287a68a0-6861-4070-819c-e4f6b3719a7f.png)

It's the inference config

**Comment by aixiaodewugege** [comment]
Thanks , I will have a try.

**Comment by aixiaodewugege** [comment]
Apologies for the interruption, but I'm trying to execute your model on my personal dataset. Currently, I am conducting inference on multiple GPUs. As my data is not annotated, I don't require the evaluation step; I just need the inference results for each image. Could you provide guidance on this matter?

Additionally, could you instruct me where I could change the label names from COCO to LVIS?

**Comment by TempleX98** [comment]
1. sh tools/slurm_test.sh partition job_name path_to_config path_to_checkpoint --format-only --options "jsonfile_prefix=./lvis_results"
2. Use `dataset_type = 'LVISV1Dataset'` in the config

**Comment by aixiaodewugege** [comment]
Hi, I'm looking to classify over 1000+ categories in my dataset and need to execute only the inference part. However, I've noticed that LVISV1Dataset is generally used for segmentation tasks. I'm wondering if it could still be applicable for my classification needs.

Besides, how should I organize my dataset? Since I don't have annotation file, but I have to input a annotation file into config.

**Comment by TempleX98** [comment]
1. Maybe you can use `CocoDataset` but you need to replace its `CLASSES` with the `CLASSES` of LVIS dataset.
2. You should organize the dataset following the [COCO test](http://images.cocodataset.org/annotations/image_info_test2017.zip) format.

**Comment by aixiaodewugege** [comment]
Hi, is LSJ means this checkpoint is trained for segmentation?

I noticed that you got a very high score on LVIS detection, could you please share this checkpoint?
![image](https://github.com/Sense-X/Co-DETR/assets/47085237/9fc7da6a-ffaa-4cd0-98e0-2f96f539245d)

**Comment by TempleX98** [comment]
LSJ means large scale jitter with copy-paste augmentation.
We do not plan to release ViT-L weights now.
