### ISSUE TITLE
How to finetune on LVIS?

### ISSUE THREAD

**Issue by aixiaodewugege** [Sense-X/Co-DETR#22]
Hi, thanks for your brilliant work!

It is amazing that you got 71.9 box AP and 59.7 mask AP on LVIS minival. But what is the difference between 71.9 box ap with `Co-DINO Swin-L 36 LSJ LVIS 56.9 config`? 56.9 is much lower than 71.9.

Can you show some details that how I can finetune on LVIS?

**Comment by TempleX98** [comment]
For 71.9 AP model, we use ViT-L and evaluate it on LVIS minival (a subset of LVIS val). And we adopt the same test setting as EVA-02 (top1000).

**Comment by TempleX98** [comment]
FedLoss is used when finetuning on LVIS
