### ISSUE TITLE
使用自己数据集训练co_dino_5scale_r50_1x_coco模型报错。。。

### ISSUE THREAD

**Issue by RedstoneWill** [Sense-X/Co-DETR#34]
作者大大您好！使用自己的数据集，我在训练co_deformable_detr_r50_1x_coco时没有报错，但是训练co_dino_5scale_r50_1x_coco时出现了以下错误：

`During handling of the above exception, another exception occurred:

Traceback (most recent call last):
    return DETECTORS.build(  File "tools/train.py", line 245, in <module>

  File "/opt/conda/lib/python3.8/site-packages/mmcv/utils/registry.py", line 215, in build
    main()
  File "tools/train.py", line 213, in main
    return self.build_func(*args, **kwargs, registry=self)
      File "/opt/conda/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
main()
  File "tools/train.py", line 213, in main
    main()
  File "tools/train.py", line 213, in main
            main()return build_from_cfg(cfg, registry, default_args)model = build_detector(

  File "tools/train.py", line 213, in main
  File "/opt/conda/lib/python3.8/site-packages/mmdet/models/builder.py", line 58, in build_detector
  File "/opt/conda/lib/python3.8/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    model = build_detector(
  File "/opt/conda/lib/python3.8/site-packages/mmdet/models/builder.py", line 58, in build_detector
        return DETECTORS.build(raise type(e)(f'{obj_cls.__name__}: {e}')

  File "/opt/conda/lib/python3.8/site-packages/mmcv/utils/registry.py", line 215, in build
AssertionError: CoDETR: CoDINOHead: The classification weight for loss and matcher should beexactly the same.
`

重点是：AssertionError: CoDETR: CoDINOHead: The classification weight for loss and matcher should beexactly the same.这一行报错不知道啥原因。

希望作者大大及各位大佬帮忙看一下问题出现在什么地方？感谢！！！

**Comment by TempleX98** [comment]
1. 删除`mmdet/models/dense_heads/detr_head.py`中的assertion部分代码
2. 使用Co-DETR codebase自带的mmdet

**Comment by RedstoneWill** [comment]
感谢您的回复！但是具体操作还不是很清楚，按照README，训练co_deformable_detr_r50_1x_coco时没有报错，但是训练co_dino_5scale_r50_1x_coco出现错误。请问作者大大在GitHub上有没有比较详细的配置步骤呢？

**Comment by RedstoneWill** [comment]
感谢您的回复！但是具体操作还不是很清楚，按照README，训练co_deformable_detr_r50_1x_coco时没有报错，但是训练co_dino_5scale_r50_1x_coco出现错误。请问作者大大在GitHub上有没有比较详细的配置步骤呢？

**Comment by TempleX98** [comment]
删除`detr_head.py`中的
`            assert loss_cls['loss_weight'] == assigner['cls_cost']['weight'], \
                'The classification weight for loss and matcher should be' \
                'exactly the same.'
            assert loss_bbox['loss_weight'] == assigner['reg_cost'][
                'weight'], 'The regression L1 weight for loss and matcher ' \
                'should be exactly the same.'
            assert loss_iou['loss_weight'] == assigner['iou_cost']['weight'], \
                'The regression iou weight for loss and matcher should be' \
                'exactly the same.'`

**Comment by RedstoneWill** [comment]
> 删除`detr_head.py`中的 ` assert loss_cls['loss_weight'] == assigner['cls_cost']['weight'], \ 'The classification weight for loss and matcher should be' \ 'exactly the same.' assert loss_bbox['loss_weight'] == assigner['reg_cost'][ 'weight'], 'The regression L1 weight for loss and matcher ' \ 'should be exactly the same.' assert loss_iou['loss_weight'] == assigner['iou_cost']['weight'], \ 'The regression iou weight for loss and matcher should be' \ 'exactly the same.'`

作者大大，为何我在mmdet/models/dense_heads/detr_head.py文件中没有找到您上面提到的这些assert语句呢？所有的文件是从github直接clone下来的~

**Comment by TempleX98** [comment]
During handling of the above exception, another exception occurred:
上面的报错也截一下

**Comment by TempleX98** [comment]
File "/opt/conda/lib/python3.8/site-packages/mmdet/models/dense_heads/detr_head.py", line 110, in init
assert loss_cls['loss_weight'] == assigner['cls_cost']['weight'],
出错的是你环境pip下载的mmdet，你可以把这个mmdet删了然后用co-detr codebase的

**Comment by RedstoneWill** [comment]
> File "/opt/conda/lib/python3.8/site-packages/mmdet/models/dense_heads/detr_head.py", line 110, in init assert loss_cls['loss_weight'] == assigner['cls_cost']['weight'], 出错的是你环境pip下载的mmdet，你可以把这个mmdet删了然后用co-detr codebase的

谢谢作者大大！原来一直是这个问题，太感谢了！！！
