### ISSUE TITLE
Self-dataset training problem

### ISSUE THREAD

**Issue by shuaixinxin** [Sense-X/Co-DETR#39]
problem: AssertionError: The `num_classes` (4) in CoDeformDETRHead of MMDataParallel does not matches the length of `CLASSES` 80) in CocoDataset

**Comment by shuaixinxin** [comment]
作者您好,我自己的数据集只有4个类别应该如何修改呢？我想修改训练时的图像尺寸的大小，应该如何修改代码呢？望指导，万分感谢！

**Comment by TempleX98** [comment]
@shuaixinxin , Hi, you can refer to this [tutorial](https://github.com/Sense-X/Co-DETR/blob/73e72fe865f1fe7d50992285d127a824684a842e/docs/en/tutorials/customize_dataset.md?plain=1#L1) for custom dataset training.
The image resolution can be modified in the [config](https://github.com/Sense-X/Co-DETR/blob/73e72fe865f1fe7d50992285d127a824684a842e/projects/configs/co_dino/co_dino_5scale_r50_1x_coco.py#L240C1-L240C15).
