### ISSUE TITLE
测试Flops时报错

### ISSUE THREAD

**Issue by eden-zhou** [Sense-X/Co-DETR#41]
报错行输出：flops, params = get_model_complexity_info(model, (3, 256, 256), as_strings=True, print_per_layer_stat=True)
  File "C:\Users\j\anaconda3\envs\Co_DETR\lib\site-packages\ptflops\flops_counter.py", line 37, in get_model_complexity_info
报错：NotImplementedError
修改参数：parser.add_argument('--config', default="D:/YOLO/Co-DETR-main/projects/configs/co_dino/co_dino_5scale_r50_1x_coco.py", help='train config file path')
希望作者给予回复，十分感谢

**Comment by TempleX98** [comment]
我已经更新了`forward_dummy`，你可以再试一下。不过不推荐使用mmdet的flops计算工具来计算Co-DETR的flops，因为某些操作比如Deformable Attention不会被统计。
