### ISSUE TITLE
mmcv version

### ISSUE THREAD

**Issue by wxysgxxn** [Sense-X/Co-DETR#42]
could you tell me the version of your mmcv.
if I use the latest version(>=2.0.0), the error is "No module named 'mmcv.parallel' "
if I use the 1.4.0 version, the error is "No module named 'mmcv._ext' "
Thanks for  your help in advance.

**Comment by TempleX98** [comment]
we use mmcv v1.5.0

**Comment by bluceliuljx** [comment]
mim install "mmcv-full==1.5.0"
only this way can be succeed
