### ISSUE TITLE
torch.distributed.elastic.multiprocessing.api:failed

### ISSUE THREAD

**Issue by wxysgxxn** [Sense-X/Co-DETR#44]
![Uploading image.png…]()
When I ran it, I got this error.
I just changed the config :   bash tools/dist_train.sh projects/configs/co_dino/co_dino_5scale_swin_large_16e_o365tococo.py 4 run

**Comment by wxysgxxn** [comment]
![1693838629403](https://github.com/Sense-X/Co-DETR/assets/67133799/2419e675-ea8d-41d9-bfbb-8dabd2e09c32)

**Comment by TempleX98** [comment]
This issue https://github.com/open-mmlab/mmcv/issues/1969 may help you

**Comment by zhouzhen0720** [comment]
> ![1693838629403](https://user-images.githubusercontent.com/67133799/265490280-2419e675-ea8d-41d9-bfbb-8dabd2e09c32.jpg)

Hello, I also encountered the same issue. Did you manage to resolve it in the end?

**Comment by zhouzhen0720** [comment]
Thank you for your reply. I have already solved this error by adding the "classes" information in the "train" section of the data dictionary in the config file.
