### ISSUE TITLE
Is there  any other code released that uses other methods as an auxiliary method(except atss)?

### ISSUE THREAD

**Issue by baron0830** [Sense-X/Co-DETR#48]
Is there  any other code released that uses other methods as an auxiliary method(except atss)?
Thank for your reply!

**Comment by TempleX98** [comment]
We use ATSS and Faster-RCNN auxiliary heads by default. Besides, the Mask-RCNN auxiliary method can be found [here](https://github.com/Sense-X/Co-DETR/blob/main/projects/configs/co_deformable_detr/co_deformable_detr_mask_r50_1x_coco.py).
