### ISSUE TITLE
The weights of the pretrained model swin_large_patch4_window12_384_22k.pth does not exist

### ISSUE THREAD

**Issue by MarouaneMja** [Sense-X/Co-DETR#51]
Hello,

 I wanted to test the last model object365 pretrained CO-Detr, but thhe weights of the pretrained model swin_large_patch4_window12_384_22k.pth does not exist as described in the config file: 
![image](https://github.com/Sense-X/Co-DETR/assets/59453891/1864c6bd-0b6c-431c-a763-9a3aeb2f09ab)

**Comment by TempleX98** [comment]
If you only want to test this model, you can simply set `load_from=None` and `pretrained=None`.

**Comment by MarouaneMja** [comment]
Thank you, but I want to train the model later for my custom dataset, the weights swin_large_patch4_window12_384_22k.pth of the pretrained model are not released yes?

**Comment by TempleX98** [comment]
You can download it here: https://github.com/SwinTransformer/storage/releases/download/v1.0.0/swin_large_patch4_window12_384_22k.pth

**Comment by MarouaneMja** [comment]
Thank you a lot, I downloaded the weights , I test it, it's working fine. I close the issue.
