### ISSUE TITLE
About export model

### ISSUE THREAD

**Issue by Egorundel** [Sense-X/Co-DETR#53]
Hello!

Is it possible to export your model to ONNX, and then to TensorRT engine to use in C++ inference?

Best wishes,
Egor

**Comment by TempleX98** [comment]
Our repo is built upon mmdet v2.x, you can refer to the [mmdet v3.x Co-DETR repo](https://github.com/open-mmlab/mmdetection/tree/dev-3.x/projects/CO-DETR) and MMDeploy for more details about model export.
