### ISSUE TITLE
Training monitoring

### ISSUE THREAD

**Issue by MarouaneMja** [Sense-X/Co-DETR#54]
Hello ,

I can't use tensorboard to monitor my training in real time, is there any alernative for tensorboard please ? Or a specific documentation on how to use for this project? 

Sincerely,
Marouane

**Comment by TempleX98** [comment]
You can use the `TensorboardLoggerHook` in your config like this:
```
log_config = dict(
    interval=50,
    hooks=[
        dict(type='TextLoggerHook'),
        dict(type='TensorboardLoggerHook')
    ])
```

**Comment by MarouaneMja** [comment]
Okey, I will try this. Thank you
