### ISSUE TITLE
SWIN-L LVIS finetuned co-dino can't load model

### ISSUE THREAD

**Issue by ronslos** [Sense-X/Co-DETR#55]
When running inference with the model I get the following error

The model and loaded state dict do not match exactly

size mismatch for roi_head.0.bbox_head.fc_cls.weight: copying a param with shape torch.Size([1203, 1024]) from checkpoint, the shape in current model is torch.Size([1204, 1024]).
size mismatch for roi_head.0.bbox_head.fc_cls.bias: copying a param with shape torch.Size([1203]) from checkpoint, the shape in current model is torch.Size([1204]).
unexpected key in source state_dict: query_head.loss_cls.fed_loss_weight, roi_head.0.bbox_head.loss_cls.fed_loss_weight, bbox_head.0.loss_cls.fed_loss_weight

/mnt/shared/ronslos/Co-DETR/mmdet/apis/inference.py:52: UserWarning: Class names are not saved in the checkpoint's meta data, use coco classes.
  warnings.warn(f'Class names are not saved in the checkpoint\'s '
/mnt/shared/ronslos/Co-DETR/mmdet/datasets/utils.py:66: UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.
  warnings.warn(
/mnt/shared/ronslos/Co-DETR/mmdet/models/utils/positional_encoding.py:81: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  dim_t = self.temperature**(2 * (dim_t // 2) / self.num_feats)
/mnt/shared/ronslos/Co-DETR/projects/models/transformer.py:476: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  dim_t = 10000**(2 * (dim_t // 2) / pos_feat)
/mnt/shared/ronslos/Co-DETR/projects/models/co_deformable_detr_head.py:1031: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  bbox_index = indexes // self.num_classes
Traceback (most recent call last):
  File "demo/image_demo.py", line 69, in <module>
    main(args)
  File "demo/image_demo.py", line 39, in main
    show_result_pyplot(
  File "/mnt/shared/ronslos/Co-DETR/mmdet/apis/inference.py", line 242, in show_result_pyplot
    model.show_result(
  File "/mnt/shared/ronslos/Co-DETR/mmdet/models/detectors/base.py", line 338, in show_result
    img = imshow_det_bboxes(
  File "/mnt/shared/ronslos/Co-DETR/mmdet/core/visualization/image.py", line 302, in imshow_det_bboxes
    bbox_palette = palette_val(get_palette(bbox_color, max_label + 1))
  File "/mnt/shared/ronslos/Co-DETR/mmdet/core/visualization/palette.py", line 61, in get_palette
    assert len(dataset_palette) >= num_classes, \
AssertionError: The length of palette should not be less than `num_classes`.

I am using the provided [config](https://github.com/Sense-X/Co-DETR/blob/main/projects/configs/co_dino/co_dino_5scale_swin_large_16e_o365tolvis.py) and [weight](https://drive.google.com/drive/folders/1nAXOkzqrEgz-YnXxIEs4d5j9li_kmrnv?usp=sharing) file

**Comment by TempleX98** [comment]
Can you evaluate the model using the config and weight to obtain 64.5 AP?

**Comment by heyitsguay** [comment]
I'm also getting this error with the ViT-L LVIS model. How was this resolved?

**Comment by paulu** [comment]
Set option `--palette random` and edit `demo/image_demo.py` as follows

```
    +from mmdet.core import DatasetEnum
    -    model = init_detector(args.config, args.checkpoint, device=args.device)
    +    model = init_detector(args.config, checkpoint=args.checkpoint, dataset=DatasetEnum.LVIS, device=args.device)
```
