### ISSUE TITLE
当前给出的配置文件中，有k=2的样例嘛，是否可以给出参考

### ISSUE THREAD

**Issue by RicoJYang** [Sense-X/Co-DETR#59]
还有个问题：在'co_dino_5scale_swin_large_16e_o365tococo.py'中，我发现最后输出的结果中没有使用上nms，如何修改配置文件使得最后的输出结果中使用nms呢？感谢作者大大！

**Comment by TempleX98** [comment]
默认的配置文件就是k=2。然后默认也使用了nms，nms只对52 AP左右的模型有作用，在更大的模型上不涨点，可以去掉
