### ISSUE TITLE
About the performance of COCO14?

### ISSUE THREAD

**Issue by Colezwhy** [Sense-X/Co-DETR#61]
Have anyone trained co-deformable DETR + R50 with 12epochs on COCO2014 dataset?
I wonder what is the performance of it when testing on COCO2014val.

**Comment by TempleX98** [comment]
We have not tried Co-DETR on the COCO2014

**Comment by Colezwhy** [comment]
> We have not tried Co-DETR on the COCO2014

Thank you,  and i will try it myself.
