### ISSUE TITLE
多尺度测试报错

### ISSUE THREAD

**Issue by 6098669** [Sense-X/Co-DETR#63]
请问如何使用多尺度测试呢

**Comment by TempleX98** [comment]
目前并不支持多尺度测试，如果想要使用多尺度测试，可以参考mmdet下的其他算法例如cascade rcnn等实现`aug_test`方法。

**Comment by dhddxdhd** [comment]
> 目前并不支持多尺度测试，如果想要使用多尺度测试，可以参考mmdet下的其他算法例如cascade rcnn等实现`aug_test`方法。

请问我只有2张显卡，那么我在跑的时候需要改学习率吗

**Comment by TempleX98** [comment]
@dhddxdhd 假如使用的模型config里的学习率是2e-4，你使用了2张显卡，每张卡上有2张图，那你的最终batch size就是2*2=4，config里的默认batch size是2*8=16，那你最终的学习率就是2e-4*4/16=5e-5
