### ISSUE TITLE
ViT-L checkpoint

### ISSUE THREAD

**Issue by zen-d** [Sense-X/Co-DETR#7]
Hi @TempleX98 , thanks for your awesome work.

> [07/03/2023] Co-DETR with [ViT-L](https://github.com/baaivision/EVA/tree/master/EVA-02) (304M parameters) sets a new record of 65.6 AP on COCO test-dev, surpassing the previous best model [InternImage-G](https://github.com/OpenGVLab/InternImage) (~3000M parameters).

Will you release the checkpoint of this ViT-L model? If yes, may I know the schedule? Thanks.

**Comment by TempleX98** [comment]
We will release the code for this model (Co-DINO) in a few weeks.

**Comment by TempleX98** [comment]
We do not plan to release it now

**Comment by TempleX98** [comment]
We pretrain the same model as the released part and evaluate it with TTA on COCO. For ViT-L from EVA-02, we use the IN-1k finetuned version `eva02_L_pt_m38m_medft_in21k_ft_in1k_p14`.

**Comment by suilin0432** [comment]
> We pretrain the same model as the released part and evaluate it with TTA on COCO. For ViT-L from EVA-02, we use the IN-1k finetuned version `eva02_L_pt_m38m_medft_in21k_ft_in1k_p14`.

Hi~ Thanks for your great job! I noticed that you mentioned evaluating the model using ViT-L(EVA-02) as the backbone with TTA on COCO.  Could you please provide me with the test config or tell me more details on how to perform TTA with EVA-02 model? Thanks a lot!

**Comment by liangt** [comment]
> 

hi, thanks for your great job! Could you please provide me with the single-scale result (and the corresponding input size) on COCO? Thanks a lot!

**Comment by liangt** [comment]
> We pretrain the same model as the released part and evaluate it with TTA on COCO. For ViT-L from EVA-02, we use the IN-1k finetuned version `eva02_L_pt_m38m_medft_in21k_ft_in1k_p14`.

hi, thanks for your great job! Could you please provide me with the single-scale result (and the corresponding input size) on COCO? Thanks a lot!

**Comment by Sense-X** [comment]
> > We pretrain the same model as the released part and evaluate it with TTA on COCO. For ViT-L from EVA-02, we use the IN-1k finetuned version `eva02_L_pt_m38m_medft_in21k_ft_in1k_p14`.
> 
> Hi~ Thanks for your great job! I noticed that you mentioned evaluating the model using ViT-L(EVA-02) as the backbone with TTA on COCO. Could you please provide me with the test config or tell me more details on how to perform TTA with EVA-02 model? Thanks a lot!

TTA has not been supported in this repo

**Comment by TempleX98** [comment]
> > We pretrain the same model as the released part and evaluate it with TTA on COCO. For ViT-L from EVA-02, we use the IN-1k finetuned version `eva02_L_pt_m38m_medft_in21k_ft_in1k_p14`.
> 
> hi, thanks for your great job! Could you please provide me with the single-scale result (and the corresponding input size) on COCO? Thanks a lot!

65.3 AP on COCO val, 1280x2048
