### ISSUE TITLE
预训练模型能否放到其他网盘上？

### ISSUE THREAD

**Issue by m00nLi** [Sense-X/Co-DETR#71]
预训练模型，能否提供一个其他网盘的链接，比如某度、某里网盘？谷歌网盘根本访问不了啊

**Comment by TempleX98** [comment]
后面会考虑放到github的release里

**Comment by YingjianYu** [comment]
期待能够放到国内可以访问的网盘，谷歌访问不了

**Comment by m00nLi** [comment]
在天朝，翻墙是违法的吧。。。
不怕跨省追捕，没收违法所得吗。。。。。。。。。。。。。

**Comment by TempleX98** [comment]
@m00nLi @YingjianYu ，你们需要哪几个模型的ckpt

**Comment by TempleX98** [comment]
@m00nLi @YingjianYu ，也可以试试官方mmdetection3.0提供的链接能不能下载，https://github.com/open-mmlab/mmdetection/tree/main/projects/CO-DETR

**Comment by YingjianYu** [comment]
@TempleX98  谢谢，mmdetection3.0提供的链接能下载
