### ISSUE TITLE
关于训练配置文件Co-DINO-Deformable-DETR

### ISSUE THREAD

**Issue by JingRD** [Sense-X/Co-DETR#73]
在论文中看到了作者提供了有关Co-DINO-Deformable-DETR配置的训练结果，但是源码中只有Co-DINO和Co-Deformable-DETR系列的配置文件，请问作者是否提供或者如何实现Co-DINO-Deformable-DETR配置文件呢，谢谢！

**Comment by TempleX98** [comment]
Co-DINO是Co-DINO-Deformable-DETR的简写，是同一个模型
