### ISSUE TITLE
encoder loss

### ISSUE THREAD

**Issue by yimeng436** [Sense-X/Co-DETR#78]
I don't understand why the label label is set to zero when the result of encoder is used to calculate the loss. Can you give me some guidance? Thank you very much

![image](https://github.com/Sense-X/Co-DETR/assets/71911179/8e08ae05-3a55-43f0-b2fc-32b160304a56)

**Comment by TempleX98** [comment]
I guess deformable-detr just follows the design of Faster-RCNN, which uses an RPN to classify the generated proposals into foreground or background.

**Comment by yimeng436** [comment]
That is to say, here the all-zero label, zero represents the foreground ?

**Comment by TempleX98** [comment]
> That is to say, here the all-zero label, zero represents the foreground ?

Yes
