### ISSUE TITLE
DetrTransformerEncoder:__init__()got an unexpected keyword argument’with_cp’

### ISSUE THREAD

**Issue by Yvette1993** [Sense-X/Co-DETR#81]
Hi, Thank for your great jobs. 
When I run the dist_train.sh for the co_dino_5scale_swin_large_1x_coco.py model got an TypeError：CoDETR:CoDINOHead:CoDinoTransformer:DeterTransformerEncoder:__init__() got an unexpected keyword argument ‘with_cp’.
But I don’t meet the error when run co_deformable_detr_model. 
Please help me, thank you.

**Comment by Yvette1993** [comment]
I found the issue, Thank you

**Comment by uitamaki** [comment]
@xiaoxiaobina @JPassionQ Please make sure you are using `mmdet` included in Co-DETR rather than installing it from PyPI, as Co-DETR has made some modifications to the `mmdet` code, and you may encounter similar issues if you use mmdet installed from PyPI.

**Comment by JPassionQ** [comment]
@uitamaki Thanks very much. I've found that it was because something wrong with my config file. But still thank you!

**Comment by Emperor124** [comment]
> 非常感谢。我发现这是因为我的配置文件有问题。但还是谢谢你！

How do you modify the configuration file？thanks
