### ISSUE TITLE
为什么官网给的权重只有200多M，但我自己训练出来的权重文件是700多m

### ISSUE THREAD

**Issue by woshixiaobai2019** [Sense-X/Co-DETR#84]
这是官网的权重
![image](https://github.com/Sense-X/Co-DETR/assets/57052600/72145732-1201-478f-9704-b52e9444e95b)
这是我自己训练出来的权重
![image](https://github.com/Sense-X/Co-DETR/assets/57052600/ed85a415-f57e-4f89-93af-9118b9ef29f0)
我就用的官网给的训练的配置文件`projects/configs/co_deformable_detr/co_deformable_detr_r50_1x_coco.py`,

**Comment by TempleX98** [comment]
自己训练的还包括optimizer和meta
