### ISSUE TITLE
ModuleNotFoundError: No module named 'mmengine'

### ISSUE THREAD

**Issue by josh3255** [Sense-X/Co-DETR#9]
When create and run a docker image using a Dockerfile, the following error occurs.

```bash
ModuleNotFoundError: No module named 'mmengine'
```

After that, install and run mmengine using pip, the following error occurs.

```bash
AssertionError: MMCV==1.3.17 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.1.0.
```

**Comment by josh3255** [comment]
okay. i'll fix it and make a pull request.

**Comment by 858949416** [comment]
> When create and run a docker image using a Dockerfile, the following error occurs.
> 
> ```shell
> ModuleNotFoundError: No module named 'mmengine'
> ```
> 
> After that, install and run mmengine using pip, the following error occurs.
> 
> ```shell
> AssertionError: MMCV==1.3.17 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.1.0.
> ```

How was it resolved in the end?
