### ISSUE TITLE
For instance segmentation

### ISSUE THREAD

**Issue by SAWRJJ** [Sense-X/Co-DETR#94]
I noticed that your model achieves SOTA results on the LVIS instance segmentation dataset and would like to ask if you can provide the config file for instance segmentation

**Comment by sjtu-cz** [comment]
Has this problem been resolved?

**Comment by SAWRJJ** [comment]
In https://github.com/Sense-X/Co-DETR/tree/main/projects/configs/co_deformable_detr/co_deformable_detr_mask_r50_1x_coco.py

**Comment by sjtu-cz** [comment]
您好，你的邮件我已经收到~
