### ISSUE TITLE
how to freeze the backbone 

### ISSUE THREAD

**Issue by Feobi1999** [Sense-X/Co-DETR#96]
I want to train on my own dataset and I want to freeze the backbone for saving time. 
The config I use is:
`model = dict(
    backbone=dict(
        _delete_=True,
        type='SwinTransformerV1',
        embed_dim=192,
        depths=[2, 2, 18, 2],
        num_heads=[6, 12, 24, 48],
        out_indices=(0, 1, 2, 3),
        window_size=12,
        ape=False,
        drop_path_rate=0.3,
        patch_norm=True,
        use_checkpoint=True,
        pretrained=pretrained,
        **frozen_stages=3,**
    ),`
   But I get the error like 
![image](https://github.com/Sense-X/Co-DETR/assets/35750924/0a0d7154-1be4-457e-85f1-a21338e93db5)

**Comment by Feobi1999** [comment]
When I set the find_unused_parameters = True, there will be another error 
![Uploading e8cb1e89-a167-493b-a389-c24596afd041.jpeg…]()

**Comment by Feobi1999** [comment]
> Can you show me your training config here?

I just modify the backbone part with a frozen parameter.
![image](https://github.com/Sense-X/Co-DETR/assets/35750924/b308b56a-ce7d-41f0-9bf1-29344d19fe5d)

**Comment by TempleX98** [comment]
I use the config `projects/configs/co_dino/co_dino_5scale_swin_large_1x_coco.py` with the backbone parameter `frozen_stages=3` and it works.  Please set `use_checkpoint` to False in the backbone config.

**Comment by Feobi1999** [comment]
Do I need to set the find_unused_parameters = True？

> I use the config `projects/configs/co_dino/co_dino_5scale_swin_large_1x_coco.py` with the backbone parameter `frozen_stages=3` and it works. Please set `use_checkpoint` to False in the backbone config.

**Comment by TempleX98** [comment]
> Do I need to set the find_unused_parameters = True？
> 
> > I use the config `projects/configs/co_dino/co_dino_5scale_swin_large_1x_coco.py` with the backbone parameter `frozen_stages=3` and it works. Please set `use_checkpoint` to False in the backbone config.

No

**Comment by Feobi1999** [comment]
Oh, I set use_checkpoint to false and it works, thanks so much
