### ISSUE TITLE
How large GPU memory will it cost to train a CO-DETR model (Swin-L)?

### ISSUE THREAD

**Issue by 1800012973** [Sense-X/Co-DETR#97]
Thanks for the great work. Only the memory of CO-deformable-DETR is mentioned in the paper, so I wonder how large gpu memory it will cost for training a CO-DETR (Swin-L)? Is 24 GB memory capable of it?

**Comment by 1800012973** [comment]
Or CO-DETR (R50)? I only have GPUs with 24 GB memory. Thanks.

**Comment by TempleX98** [comment]
It is sufficient to train a SwinL Co-DETR with 24GB GPUs. Please refer to this [link](https://github.com/open-mmlab/mmdetection/tree/main/projects/example_largemodel) for more details.

**Comment by 1800012973** [comment]
Thanks!
